# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/lucasmbrown/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            '--in-place',
            '--remove-all-unused-imports',
            '--ignore-init-module-imports',
            '--remove-unused-variable',
          ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/ambv/black
    rev: master
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: fix-encoding-pragma
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - toml
          - flake8-assertive
          - flake8-blind-except
          - flake8-builtins
          - flake8-coding
          - flake8-comprehensions
          - flake8-isort
          - flake8-logging-format
          - flake8-mutable
          - flake8-print
          - pep8-naming
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
        args: ['--single-quote', '--trailing-comma', 'es5']
