language: python
python:
  - 2.7
before_install:
  - sudo apt-get install pandoc
  - npm install casperjs
cache:
- pip
- apt

before_script:
  - psql -c 'create database hasjob;' -U postgres
  - python manage.py db create -e testing
  - python runtestserver.py

script: casperjs test tests/test-suite.js

addons:
  postgresql: "9.3"

services:
  - redis-server

notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
