language: python
python:
  - 2.7
before_install:
  - sudo apt-get install pandoc
  - npm install casperjs
  - wget -O - http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz | sudo gunzip -c > /usr/share/GeoIP/GeoLite2-City.mmdb
cache:
- pip
- apt

before_script:
  - psql -c 'create database hasjob;' -U postgres
  - python manage.py db create
  - python runtestserver.py

script: casperjs test tests/test-suite.js

addons:
  postgresql: "9.3"

notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
