language: python
python:
  - 2.7
before_script:
  - npm install casperjs
  - python manage.py db create
  - python runserver.py
script: casperjs test tests/test-suite.js
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
