language: python
python:
  - 3.7
before_script:
  - psql -c 'create database hasjob_testing;' -U postgres
install:
  - pip install -U pip wheel
  - pip install --no-cache-dir -r test_requirements.txt
  - pip install --no-cache-dir -r requirements.txt
  - npm install casperjs
  - make
script: ./runtests.sh
after_success:
  - coveralls
addons:
  postgresql: "9.4"
services:
  - redis-server
notifications:
  email: false
