"""Adding datetime column

Revision ID: 33de75e55858
Revises: 525b125ec799
Create Date: 2015-10-10 12:32:39.936107

"""

# revision identifiers, used by Alembic.
revision = '33de75e55858'
down_revision = '525b125ec799'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_anon_view', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_campaign_anon_view_datetime'), 'campaign_anon_view', ['datetime'], unique=False)
    op.add_column('campaign_view', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_campaign_view_datetime'), 'campaign_view', ['datetime'], unique=False)
    op.drop_index('ix_domain_search_vector', table_name='domain')
    op.add_column('job_impression', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_job_impression_datetime'), 'job_impression', ['datetime'], unique=False)
    op.add_column('job_view_session', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_job_view_session_datetime'), 'job_view_session', ['datetime'], unique=False)
    op.drop_index('ix_jobpost_search_vector', table_name='jobpost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobpost_search_vector', 'jobpost', ['search_vector'], unique=False)
    op.drop_index(op.f('ix_job_view_session_datetime'), table_name='job_view_session')
    op.drop_column('job_view_session', 'datetime')
    op.drop_index(op.f('ix_job_impression_datetime'), table_name='job_impression')
    op.drop_column('job_impression', 'datetime')
    op.create_index('ix_domain_search_vector', 'domain', ['search_vector'], unique=False)
    op.drop_index(op.f('ix_campaign_view_datetime'), table_name='campaign_view')
    op.drop_column('campaign_view', 'datetime')
    op.drop_index(op.f('ix_campaign_anon_view_datetime'), table_name='campaign_anon_view')
    op.drop_column('campaign_anon_view', 'datetime')
    ### end Alembic commands ###
